"use client";

import { useCallback, useEffect, useState } from "react";
import {
  AlertTriangle,
  Download,
  FileLock2,
  Loader2,
  Plus,
  ShieldCheck,
  Trash2,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Checkbox } from "@/components/ui/checkbox";
import { ApiError, api, getUserSessionId, type IncidentDraft, type ReportingRoute } from "@/lib/api";

export default function ReportPage() {
  const [content, setContent] = useState("");
  const [notes, setNotes] = useState("");
  const [consent, setConsent] = useState(false);
  const [drafts, setDrafts] = useState<IncidentDraft[]>([]);
  const [routes, setRoutes] = useState<ReportingRoute[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [savedDraft, setSavedDraft] = useState<IncidentDraft | null>(null);

  const refresh = useCallback(async () => {
    try {
      const sessionId = getUserSessionId();
      const [d, r] = await Promise.all([api.listDrafts(sessionId), api.getReportingRoutes()]);
      setDrafts(d.drafts);
      setRoutes(r.routes);
    } catch (e) {
      // The locker is optional; show the error but keep the composer usable.
      setError(e instanceof ApiError ? e.message : "Could not load your drafts.");
    }
  }, []);

  useEffect(() => {
    // Initial load of the user's drafts; refresh() sets state in promise
    // callbacks only, but the rule flags the synchronous call itself.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    refresh();
  }, [refresh]);

  const handleCreate = async () => {
    setError(null);
    setSavedDraft(null);
    if (!content.trim()) return;
    setIsLoading(true);
    try {
      const draft = await api.createDraft({
        user_session_id: getUserSessionId(),
        content,
        notes: notes || undefined,
        consent_storage: consent,
      });
      setSavedDraft(draft);
      setContent("");
      setNotes("");
      setConsent(false);
      if (draft.draft_id !== "local-only") await refresh();
    } catch (e) {
      setError(e instanceof ApiError ? e.message : "Could not create the draft.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDelete = async (draftId: string) => {
    setError(null);
    try {
      await api.deleteDraft(draftId, getUserSessionId());
      setDrafts((prev) => prev.filter((d) => d.draft_id !== draftId));
    } catch (e) {
      setError(e instanceof ApiError ? e.message : "Could not delete the draft.");
    }
  };

  const exportDraft = (draft: IncidentDraft) => {
    const lines = [
      "NiveshRaksha — Incident Evidence Draft",
      `Created: ${new Date(draft.created_at).toLocaleString()}`,
      "",
      "REDACTED CONTENT (sensitive identifiers were removed before storage):",
      draft.redacted_content,
      "",
      "NOTES:",
      draft.notes ?? "(none)",
      "",
      "OFFICIAL REPORTING ROUTES:",
      ...routes.map((r) => `- ${r.name}: ${r.url} (${r.use})`),
      "",
      "Disclaimer: This draft was generated by a safety tool. It is not legal advice.",
      "Report online fraud at https://cybercrime.gov.in or call 1930.",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `niveshraksha-incident-${draft.draft_id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 sm:p-6">
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-3">
            <FileLock2 className="h-8 w-8 text-teal-600" aria-hidden /> Evidence Locker
          </h1>
          <p className="text-slate-600 dark:text-slate-400 mt-2">
            Prepare a private, redacted incident draft you can use when reporting to official channels. Nothing is submitted anywhere automatically.
          </p>
        </div>

        <Card className="mb-8">
          <CardHeader>
            <CardTitle>New incident draft</CardTitle>
            <CardDescription>
              Paste the suspicious message or describe what happened. Identifiers such as phone numbers, PAN, Aadhaar, UPI IDs and emails are redacted before anything is stored or exported.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="content">What happened / the message</Label>
              <Textarea
                id="content"
                className="min-h-[140px] resize-none"
                value={content}
                onChange={(e) => setContent(e.target.value)}
                placeholder="Paste the message or describe the incident..."
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="notes">Your notes (optional)</Label>
              <Input
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="e.g., received on WhatsApp on 3 Oct, number looked like..."
              />
            </div>
            <div className="flex items-start space-x-3 rounded-md border border-slate-200 dark:border-slate-800 p-3 bg-white dark:bg-slate-900">
              <Checkbox
                id="consent"
                checked={consent}
                onCheckedChange={(v) => setConsent(v)}
                className="mt-0.5"
              />
              <Label htmlFor="consent" className="text-sm font-normal text-slate-600 dark:text-slate-300">
                I consent to this draft being stored on the server, redacted, and automatically deleted after 72 hours. (Not ticked = nothing is stored; copy or export it yourself.)
              </Label>
            </div>
          </CardContent>
          <CardFooter>
            <Button
              onClick={handleCreate}
              disabled={!content.trim() || isLoading}
              className="w-full bg-teal-600 hover:bg-teal-700 text-white min-h-[48px]"
            >
              {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden /> : <Plus className="mr-2 h-4 w-4" aria-hidden />}
              Create draft (redacted)
            </Button>
          </CardFooter>
        </Card>

        {savedDraft && (
          <Alert className={savedDraft.draft_id === "local-only" ? "border-amber-600/50 bg-amber-50 dark:bg-amber-950/20 mb-8" : "border-teal-600/50 bg-teal-50 dark:bg-teal-950/20 mb-8"} aria-live="polite">
            <ShieldCheck className="h-5 w-5 text-teal-600" aria-hidden />
            <AlertTitle>{savedDraft.draft_id === "local-only" ? "Not stored (no consent given)" : "Draft created"}</AlertTitle>
            <AlertDescription className="mt-2 text-slate-700 dark:text-slate-300">
              {savedDraft.retention_note}
              <div className="mt-3 rounded-md bg-white/70 dark:bg-slate-900/70 p-3 text-xs font-mono whitespace-pre-wrap break-words border">
                {savedDraft.redacted_content}
              </div>
              {savedDraft.draft_id !== "local-only" && (
                <Button variant="outline" size="sm" className="mt-3" onClick={() => exportDraft(savedDraft)}>
                  <Download className="mr-2 h-4 w-4" aria-hidden /> Export as text
                </Button>
              )}
            </AlertDescription>
          </Alert>
        )}

        {error && (
          <Alert variant="destructive" role="alert" className="mb-8">
            <AlertTriangle className="h-5 w-5" aria-hidden />
            <AlertTitle>Locker unavailable</AlertTitle>
            <AlertDescription className="mt-2">{error}</AlertDescription>
          </Alert>
        )}

        <section aria-label="Saved drafts" className="mb-8">
          <h2 className="text-xl font-semibold mb-4 text-slate-900 dark:text-slate-100">Your drafts</h2>
          {drafts.length === 0 ? (
            <p className="text-sm text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900 border border-dashed rounded-lg p-6 text-center">
              No drafts stored. Created drafts appear here until they expire (72 hours) or you delete them.
            </p>
          ) : (
            <ul className="space-y-4">
              {drafts.map((d) => (
                <li key={d.draft_id}>
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-medium text-slate-600 dark:text-slate-300">
                        Draft {d.draft_id.slice(0, 8)} · created {new Date(d.created_at).toLocaleString()} · expires {new Date(d.expires_at).toLocaleString()}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3">
                      <p className="text-sm whitespace-pre-wrap break-words bg-slate-50 dark:bg-slate-900 border rounded p-3 font-mono text-xs">
                        {d.redacted_content}
                      </p>
                      {d.notes && <p className="text-xs text-slate-500">Notes: {d.notes}</p>}
                      <div className="flex gap-2">
                        <Button variant="outline" size="sm" onClick={() => exportDraft(d)}>
                          <Download className="mr-2 h-4 w-4" aria-hidden /> Export
                        </Button>
                        <Button variant="outline" size="sm" className="text-red-600 border-red-200 hover:bg-red-50 dark:border-red-900" onClick={() => handleDelete(d.draft_id)}>
                          <Trash2 className="mr-2 h-4 w-4" aria-hidden /> Delete now
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                </li>
              ))}
            </ul>
          )}
        </section>

        <section aria-label="Official reporting routes">
          <h2 className="text-xl font-semibold mb-4 text-slate-900 dark:text-slate-100">Where to report officially</h2>
          <div className="grid gap-4 sm:grid-cols-3">
            {routes.map((r) => (
              <a
                key={r.url}
                href={r.url}
                target="_blank"
                rel="noopener noreferrer"
                className="block bg-white dark:bg-slate-900 border rounded-lg p-4 hover:shadow transition"
              >
                <p className="font-medium text-slate-900 dark:text-slate-100 flex items-center gap-1">
                  {r.name} <ExternalLink className="h-3 w-3" aria-hidden />
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{r.use}</p>
              </a>
            ))}
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-4">
            NiveshRaksha never submits a complaint on your behalf. Reporting is your action, on official portals.
          </p>
        </section>
      </div>
    </div>
  );
}
